joint_name_to_servo_id: {
  HEAD_JOINT0: 32,
  HEAD_JOINT1: 34,
  LARM_JOINT0: 3,
  LARM_JOINT1: 5,
  LLEG_JOINT0: 1,
  LLEG_JOINT1: 21,
  RARM_JOINT0: 2,
  RARM_JOINT1: 4,
  RLEG_JOINT0: 0, 
  RLEG_JOINT1: 20
}
