joint_name_to_servo_id: {
  HEAD_JOINT0: 32,
  HEAD_JOINT1: 34,
  LARM_JOINT0: 3,
  LARM_JOINT1: 5,
  LARM_JOINT2: 23,
  LARM_JOINT3: 7,
  LARM_JOINT4: 27,
  LARM_JOINT5: 29,
  LARM_JOINT6: 19,
  LARM_JOINT7: 19,
  LLEG_JOINT0: {'id': 25, 'direction': -1},
  LLEG_JOINT1: {'id': 17, 'direction': -1},
  RARM_JOINT0: 2,
  RARM_JOINT1: 4,
  RARM_JOINT2: 22,
  RARM_JOINT3: 6,
  RARM_JOINT4: 26,
  RARM_JOINT5: 28,
  RARM_JOINT6: 18,
  RARM_JOINT7: 18,
  RLEG_JOINT0: {'id': 24, 'direction': 1},
  RLEG_JOINT1: {'id': 16, 'direction': 1}
}
